In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\Movie_Sentiment_Analysis\data\raw\IMDB.csv')
df = df.sample(500)
df.to_csv('data.csv', index=False)
df.head()

                                                review sentiment
519  "Most of us at least inhabit two worlds , the ...  positive
806  At the time, "My Left Foot" was the little mov...  positive
486  Guy Richie's third proper film (not counting t...  negative
293  I am a chess player and I wanted to like this ...  negative
511  I'm sure this is a show no one is that familia...  positive

In [3]:
df

                                                review sentiment
519  "Most of us at least inhabit two worlds , the ...  positive
806  At the time, "My Left Foot" was the little mov...  positive
486  Guy Richie's third proper film (not counting t...  negative
293  I am a chess player and I wanted to like this ...  negative
511  I'm sure this is a show no one is that familia...  positive
..                                                 ...       ...
303  Soul Calibur is more solid than it ever was......  positive
354  ''The 40 Year Old Virgin'''made me laugh a lot...  positive
588  ok we have a film that some are calling one of...  negative
999  ****SPOILER ALERT**** All throughout Australia...  positive
611  Getting lost in space frozen for 15 years, tha...  negative

[500 rows x 2 columns]

In [4]:
def clean_data(df):
    # Replace all instances of "positive" with "1" in column: 'sentiment'
    df['sentiment'] = df['sentiment'].str.replace(
        "positive", "1", case=False, regex=False)
    # Replace all instances of "negative" with "0" in column: 'sentiment'
    df['sentiment'] = df['sentiment'].str.replace(
        "negative", "0", case=False, regex=False)
    return df


df_clean= clean_data(df.copy())
df= df_clean.copy()
df.head(8)

                                                review sentiment
519  "Most of us at least inhabit two worlds , the ...         1
806  At the time, "My Left Foot" was the little mov...         1
486  Guy Richie's third proper film (not counting t...         0
293  I am a chess player and I wanted to like this ...         0
511  I'm sure this is a show no one is that familia...         1
332  There wasn't a 0 in the voting option so i was...         0
275  Tyra Banks needs to teach these girls that it'...         0
123  I sat through this on TV hoping because of the...         0

In [5]:
df['sentiment'].value_counts()

sentiment
0    254
1    246
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

0

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
x = df['review']
y= df['sentiment'].to_numpy()
cv = CountVectorizer(max_features=100)
x = cv.fit_transform(x).toarray()

In [16]:
x

array([[0, 0, 1, ..., 2, 0, 1],
       [1, 0, 2, ..., 2, 0, 0],
       [0, 0, 3, ..., 3, 2, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 5],
       [2, 0, 2, ..., 7, 0, 0],
       [1, 1, 0, ..., 3, 0, 1]], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state= 42)

In [18]:
from sklearn.linear_model import LogisticRegression 
lr= LogisticRegression()
lr.fit(x_train, y_train)
y_pred= lr.predict(x_test)

In [22]:
y_test = y_test.astype(int)
y_pred = y_pred.astype(int)

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Roc_Auc_Score: ", roc_auc_score(y_test, y_pred))

Accuracy:  0.63
Precision:  0.5384615384615384
Recall:  0.6829268292682927
F1_Score:  0.6021505376344086
Roc_Auc_Score:  0.6380735841256717